const { hasUncaughtExceptionCaptureCallback } = require('process')
const {Intern}=require('../Intern')

describe("xxxxxxxxxxxxx",()=>{

test('returns an xxxxxx',()=>{
//arrange
const name='bob'
const id= 333
const email='bajebi@mac.com'
//act
const engineer= new Employee(name,id,email)
console.log(engineer)
//assert
hasUncaughtExceptionCaptureCallback(engineer instanceof Engineer).toBe('true')

// expect(typeof employee).toBe("object")

})

it('has a name',()=>{
//arrange
//act
//assert

})
it('has a id number',()=>{
//arrange
//act
//assert

})
it('has a email',()=>{
//arrange
//act
//assert

})


})
